local map = vim.keymap.set
local scli = require("sidekick.cli")

map("i", "jk", "<Esc>", { desc = "Exit insert" })
map("i", "kj", "<Esc>", { desc = "Exit insert" })
map("t", "jk", "<C-\\><C-n>", { desc = "Exit terminal input" })
map("t", "kj", "<C-\\><C-n>", { desc = "Exit terminal input" })

-- Splits
map("n", "<C-Up>", "<CMD>resize -2<CR>", { desc = "Resize split up" })
map("n", "<C-Down>", "<CMD>resize +2<CR>", { desc = "Resize split down" })
map("n", "<C-Left>", "<CMD>vertical resize -2<CR>", { desc = "Resize split left" })
map("n", "<C-Right>", "<CMD>vertical resize +2<CR>", { desc = "Resize split right" })

-- LSP
map("n", "<leader>e", vim.diagnostic.open_float, { desc = "Explain diagnostic" })
map("n", "[d", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
map("n", "]d", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
map("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Diagnostic list" })
map("n", "<leader>f", function()
	require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "Format buffer" })
map("n", "<leader>tf", function()
	vim.b.disable_autoformat = not vim.b.disable_autoformat
	vim.notify(("Format on save: %s"):format(vim.b.disable_autoformat and "off" or "on"), vim.log.levels.INFO)
end, { desc = "Toggle format on save" })

-- FS
map("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })

-- Mini
map("n", "<leader><space>", function()
	MiniPick.builtin.files()
end, { desc = "Find files" })
map("n", "<leader>/", function()
	MiniPick.builtin.grep_live()
end, { desc = "Grep files" })
map("n", "<leader>,", function()
	MiniPick.builtin.buffers()
end, { desc = "Buffers" })
map("n", "<leader>fh", function()
	MiniPick.builtin.help()
end, { desc = "Help tags" })
map("n", "<leader>sk", function()
	require("mini.extra").pickers.keymaps({ scope = "all" })
end, { desc = "Search keymaps" })
map("n", "<leader>go", function()
	MiniDiff.toggle_overlay()
end, { desc = "Toggle Git diff overlay" })
map("n", "[c", function()
	MiniDiff.goto_hunk("prev")
end, { desc = "Previous Git change" })
map("n", "]c", function()
	MiniDiff.goto_hunk("next")
end, { desc = "Next Git change" })

-- Sidekick
map({ "n", "t", "i", "x" }, "<C-.>", function()
	scli.focus()
end, { desc = "Sidekick Focus" })
map("n", "<leader>aa", function()
	scli.toggle()
end, { desc = "Sidekick Toggle CLI" })
map("n", "<leader>as", function()
	scli.select()
end, { desc = "Select CLI" })
map("n", "<leader>ad", function()
	scli.close()
end, { desc = "Detach a CLI Session" })
map({ "n", "x" }, "<leader>at", function()
	scli.send({ msg = "{this}" })
end, { desc = "Send This" })
map("n", "<leader>af", function()
	scli.send({ msg = "{file}" })
end, { desc = "Send File" })
map("x", "<leader>av", function()
	scli.send({ msg = "{selection}" })
end, { desc = "Send Visual Selection" })
map({ "n", "x" }, "<leader>ap", function()
	scli.prompt()
end, { desc = "Sidekick Select Prompt" })
map("n", "<leader>ac", function()
	scli.toggle({ name = "codex", focus = true })
end, { desc = "Sidekick Toggle Codex" })
